aliases:
  1.webp: 等投喂
  2.webp: 委屈
  3.webp: 坏猫出没
  4.webp: 求领养
  5.webp: 嘻嘻
  6.webp: 警觉
  7.webp: 蓬松
  8.webp: 优雅
  9.webp: 不给看
  10.webp: 舔毛
  11.webp: 抖抖
  12.webp: 略
  13.webp: 无辜
  14.webp: 耍脾气
  15.webp: 踩奶
  16.webp: 睡了
  17.webp: 拒绝抱抱
  18.webp: 鲨猫头
  19.webp: 鲨猫身
  20.webp: 鲨猫尾
chinese_name: 鲨猫的牛马日常
english_name: sha-mao-de-niu-ma-ri-chang
source: 'https://www.bilibili.com/'
source_description: 表情包版权归原作者所有
tags:
- BiliBili
- 鲨猫