aliases:
  rxy_bukuishiwo.webp: "不愧是我"
  rxy_chigua.webp: "吃瓜"
  rxy_ding.webp: "顶"
  rxy_giveuflower.webp: "给你一朵花"
  rxy_han.webp: "汗"
  rxy_hi.webp: "嗨"
  rxy_justbuyit.webp: "就买它"
  rxy_loveu.webp: "爱你"
  rxy_renne.webp: "人呢"
  rxy_reversed_you.webp: "反转的你"
  rxy_sleepin.webp: "睡觉中"
  rxy_star_eyes.webp: "星星眼"
  rxy_tietie.webp: "贴贴"
  rxy_what.webp: "什么"
  rxy_yesyesyes.webp: "是的是的"
  rxy_zhizhidiandian.webp: "指指点点"
chinese_name: 日行一牡丹
english_name: rxy
source: 网络
source_description: 由 Summer 整理
tags: {}
