aliases:
  1.png: '燃起来了'
  2.png: '生气'
  3.png: '睡了'
  4.png: '贴贴'
  5.png: '哇'
  6.png: '幸福'
  7.png: '优雅'
  8.png: '愉悦'
  9.png: '尊嘟假嘟'
  10.png: '变身！'
  11.png: '盯'
  12.png: '干饭'
  13.png: '乖巧'
  14.png: '嗨'
  15.png: '哼'
  16.png: '惊'
  17.png: '来了'
  18.png: '猫猫祟祟'
  19.png: '没米了'
  20.png: '难过'
chinese_name: 豆泥大陆收藏集
english_name: dou-ni-da-lu-shou-cang-ji
source: 
source_description: BiliBili
tags: {}
