aliases:
  c-1010.svg: ''
  c-1011.svg: ''
  c-1012.svg: ''
  c-1013.svg: ''
  c-1014.svg: ''
  c-1015.svg: ''
  c-1016.svg: ''
  c-1017.svg: ''
  c-1018.svg: ''
  c-1019.svg: ''
  c-1020.svg: ''
  c-1021.svg: ''
  c-104.svg: ''
  c-105.svg: ''
  c-106.svg: ''
  c-107.svg: ''
  c-108.svg: ''
  c-109.svg: ''
  c-68.svg: ''
  c-69.svg: ''
  c-70.svg: ''
  c-71.svg: ''
  c-72.svg: ''
  c-73.svg: ''
  c-74.svg: ''
  c-75.svg: ''
  c-76.svg: ''
  c-77.svg: ''
  c-78.svg: ''
  c-79.svg: ''
  c-80.svg: ''
  c-85.svg: ''
  c-86.svg: ''
  c-87.svg: ''
  c-88.svg: ''
  c-89.svg: ''
  c-90.svg: ''
  c-91.svg: ''
  c-92.svg: ''
  c-93.svg: ''
  c-94.svg: ''
  c-aixin.svg: ''
  c-aoman.svg: ''
  c-baiyan.svg: ''
  c-baoquan.svg: ''
  c-bishi.svg: ''
  c-caidao.svg: ''
  c-chigua.svg: ''
  c-ciya.svg: ''
  c-coolb.svg: ''
  c-coshuaji.svg: ''
  c-diaoxie.svg: ''
  c-doge.svg: ''
  c-dogehechi.svg: ''
  c-dogexiaoku.svg: ''
  c-dogeyuanliangta.svg: ''
  c-doujiyanhuaji.svg: ''
  c-erha.svg: ''
  c-erhading.svg: ''
  c-fadai.svg: ''
  c-fanu.svg: ''
  c-fived.svg: ''
  c-fivef.svg: ''
  c-fivem.svg: ''
  c-fiveo.svg: ''
  c-fivey.svg: ''
  c-fy.svg: ''
  c-hahaha.svg: ''
  c-haixiu.svg: ''
  c-han.svg: ''
  c-hehe.svg: ''
  c-heiha.svg: ''
  c-heixian.svg: ''
  c-hejiu.svg: ''
  c-hongyaowan.svg: ''
  c-huaixiao.svg: ''
  c-huaji.svg: ''
  c-huanhu.svg: ''
  c-huoba.svg: ''
  c-jingya.svg: ''
  c-jizhi.svg: ''
  c-keai.svg: ''
  c-kelian.svg: ''
  c-koubi.svg: ''
  c-ku.svg: ''
  c-kuan.svg: ''
  c-kuanlvmao.svg: ''
  c-liuhanhuaji.svg: ''
  c-liulei.svg: ''
  c-lvmao.svg: ''
  c-lvyaowan.svg: ''
  c-meigui.svg: ''
  c-miaomiao.svg: ''
  c-mojinghuaji.svg: ''
  c-naikezui.svg: ''
  c-nanguo.svg: ''
  c-nb.svg: ''
  c-ok.svg: ''
  c-oned.svg: ''
  c-onef.svg: ''
  c-onem.svg: ''
  c-oneo.svg: ''
  c-oney.svg: ''
  c-oy.svg: ''
  c-pen.svg: ''
  c-penxue.svg: ''
  c-piezui.svg: ''
  c-pu.svg: ''
  c-pyjiaoyi.svg: ''
  c-qiang.svg: ''
  c-qinqin.svg: ''
  c-qqdoge.svg: ''
  c-ruo.svg: ''
  c-se.svg: ''
  c-shounuehuaji.svg: ''
  c-shui.svg: ''
  c-teny.svg: ''
  c-tuosai.svg: ''
  c-tushe.svg: ''
  c-twod.svg: ''
  c-twof.svg: ''
  c-twom.svg: ''
  c-twoo.svg: ''
  c-twoy.svg: ''
  c-ty.svg: ''
  c-weiqu.svg: ''
  c-weiweiyixiao.svg: ''
  c-weixiao.svg: ''
  c-wozuimei.svg: ''
  c-wulian.svg: ''
  c-wunai.svg: ''
  c-wuyu.svg: ''
  c-wuzuixiao.svg: ''
  c-xiaoku.svg: ''
  c-xiaoyan.svg: ''
  c-xinsui.svg: ''
  c-ye.svg: ''
  c-yinxian.svg: ''
  c-yiwen.svg: ''
  c-zaijian.svg: ''
  c-zhoumei.svg: ''
chinese_name: 酷安
english_name: coolapk
source: https://github.com/NitroRCr/coolapk-emotion
source_description: null
tags: {}
