aliases:
  admire.gif: ''
  ahhh.gif: ''
  butt.gif: ''
  catch.gif: ''
  color.gif: ''
  cry.gif: ''
  fake.gif: ''
  friend.gif: ''
  happy.gif: ''
  happynow.gif: ''
  intrigued.gif: ''
  kudos.gif: ''
  love.gif: ''
  love2.gif: ''
  love3.gif: ''
  poke.gif: ''
  question.gif: ''
  rain.gif: ''
  second.gif: ''
  shake.gif: ''
  shocked.gif: ''
  sleep.gif: ''
  spare.gif: ''
  whimper.gif: ''
  whoa.gif: ''
  work.gif: ''
  write.gif: ''
chinese_name: 咖波
english_name: capoo
source: https://flyalready.com
source_description: 由 Summer 整理
tags: {}
