aliases:
  1.webp: 浮出来
  2.webp: 哦怎？
  3.webp: 变成馒头
  4.webp: 嘲笑
  5.webp: 喜欢
  6.webp: 补药
  7.webp: 混乱
  8.webp: 我觉得海星
  9.webp: 喜欢冰块
  10.webp: 要抱抱
  11.webp: 海豹
  12.webp: 拿走
  13.webp: 漂流瓶联系
  14.webp: 哽住
  15.webp: 真正的音乐
chinese_name: 海洋奇遇记
english_name: hai-yang-qi-yu-ji
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=1754300747001&isdiy=0&part=emoji_package&from=emoji&f_source=garb&vmid=451090261&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags:
- BiliBili
