aliases:
  1.webp: ''
  10.webp: ''
  11.webp: ''
  12.webp: ''
  13.webp: ''
  14.webp: ''
  15.webp: ''
  16.webp: ''
  2.webp: ''
  3.webp: ''
  4.webp: ''
  5.webp: ''
  6.webp: ''
  7.webp: ''
  8.webp: ''
  9.webp: ''
chinese_name: 哈气咪豆浆
english_name: HachimiiSoya
source: https://t.me/addstickers/HachimiiSoya
source_description: 表情包版权归原作者所有
tags:
- Furry
