aliases:
  1.webp: 加油
  2.webp: 喝水
  3.webp: 开心
  4.webp: 蹲蹲
  5.webp: 拜拜
  6.webp: 炉子
  7.webp: 露营左
  8.webp: 露营右
  9.webp: 钓鱼上
  10.webp: 火
  11.webp: 闹钟
  12.webp: 背包
  13.webp: 杯子
  14.webp: 钓鱼下
  15.webp: 树
chinese_name: 团子硬核露营
english_name: tuan-zi-ying-he-lu-ying
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=1762744913001&isdiy=0&part=emoji_package&from=emoji&f_source=garb&vmid=451090261&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags:
- BiliBili
