aliases:
  lily鸭.webp: ''
  morry鸭.webp: ''
  不对劲.webp: ''
  呜.webp: ''
  哭哭.webp: ''
  墨镜.webp: ''
  墨镜哭.webp: ''
  委屈.webp: ''
  宕机.webp: ''
  得意.webp: ''
  心虚.webp: ''
  戳手手.webp: ''
  抱.webp: ''
  星星眼.webp: ''
  木头鸭.webp: ''
  疑问.webp: ''
  盯.webp: ''
  荷叶.webp: ''
  贴贴.webp: ''
  鱼.webp: ''
chinese_name: 心理鸭第二弹
english_name: xinliyadierdan
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=107377&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 心理鸭Psyqualogy@BiliBili
tags: {}
