aliases:
  lily鸭.jpg: ''
  morry鸭.jpg: ''
  不对劲.jpg: ''
  呜.jpg: ''
  哭哭.jpg: ''
  墨镜.jpg: ''
  墨镜哭.jpg: ''
  委屈.jpg: ''
  宕机.jpg: ''
  得意.jpg: ''
  心虚.jpg: ''
  戳手手.jpg: ''
  抱.jpg: ''
  星星眼.jpg: ''
  木头鸭.jpg: ''
  疑问.jpg: ''
  盯.jpg: ''
  荷叶.jpg: ''
  贴贴.jpg: ''
  鱼.jpg: ''
chinese_name: 心理鸭第二弹
english_name: xinliyadierdan
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=107377&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 心理鸭Psyqualogy@BiliBili
tags: {}
