aliases:
  1.webp: 抱大腿
  2.webp: 不要
  3.webp: 呆滞
  4.webp: 单纯
  5.webp: 好耶
  6.webp: 惊讶
  7.webp: 哭
  8.webp: 来了
  9.webp: 呸
  10.webp: 探头
  11.webp: 舔
  12.webp: 投币
  13.webp: 苦鲁西
  14.webp: 再见
  15.webp: 震惊
chinese_name: 暹罗猫小豆泥
english_name: xian-luo-mao-xiao-dou-ni
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=34525&isdiy=0&part=emoji_package&from=emoji&f_source=garb&vmid=451090261&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags:
- BiliBili
- 豆泥猫
