aliases:
  1.webp: 起飞
  2.webp: 蟑螂
  3.webp: 长腿
  4.webp: 期待
  5.webp: 仰头
  6.webp: 盯
  7.webp: 夜
  8.webp: 师
  9.webp: 傅
  10.webp: 墨镜
  11.webp: 酷
  12.webp: 乌
  13.webp: 一
  14.webp: 鸦
  15.webp: 紧张
chinese_name: 来份乌鸦2.0雪夜陪伴
english_name: lai-fen-wu-ya-2.0-xue-ye-pei-ban
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=1766544922001&isdiy=0&part=emoji_package&from=emoji&f_source=garb&vmid=451090261&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags:
- BiliBili
-   鸟